env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  USERID: ${{ secrets.USERID }}
  CYPRESS_ID: ${{ secrets.CYPRESS_ID }}

name: Trigger BookCart cypress tests
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, assigned, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run cy:run:bookcart -- --env USERNAME=${{ secrets.USERNAME }} --env PASSWORD=${{ secrets.PASSWORD }} --env USERID=${{ secrets.USERID }} --env projectId=${{ secrets.CYPRESS_ID }} --record --key=${{ secrets.RECORD_KEY }}
        
      - name: Generate mochawesome report
        run: npm run generate:report
        if: success()

      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          path: mochawesome-report
          name: Test report
        if: success()

      - name: Download report
        uses: actions/download-artifact@v3
        with:
          name: Test report
        if: success()
